name: untitled3
description: A new Flutter project

# Set this to "none" for local development; remove the line if publishing to pub.dev.
publish_to: none

# Versioning for your app.
version: 1.0.0+1

# Define the environment SDK version range.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  file_picker: ^8.1.4          # For selecting files (multiple formats)
    # For picking images

  # Utility dependencies
  fluttertoast: ^8.1.2         # For showing toast messages
  provider: ^6.0.0             # For state management



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Declare the assets directory
  assets:
    - assets/images/
